services:
  directus2:
    image: directus/directus:11.6.1
    environment:
      ## Secret Keys & Env
      - KEY=G8sRAyY5bN0ndpWjfHkSIzztKaPVzHTt # https://acte.ltd/utils/randomkeygen
      - SECRET=TXeJ9tixBbvM8KTcX6eTFwbx6W0tdTpP # https://acte.ltd/utils/randomkeygen
      - APP_ENV=production
      - ADMIN_EMAIL=rafaelpedr@gmail.com
      - ADMIN_PASSWORD=if5maBHrGcH2tMs
      - PUBLIC_URL=https://directus2.rafaelpedrosa.com.br
      ## 17/03/2025 Correcao para nao sair do directus e dar erro de Cookies
      - AUTH_TOKEN_EXPIRY=30d
      - REFRESH_TOKEN_EXPIRY=30d
      - REFRESH_TOKEN_COOKIE_SECURE=false
      - REFRESH_TOKEN_COOKIE_SAME_SITE=lax
      - ACCESS_TOKEN_TTL=144000m
      - SESSION_COOKIE_TTL=30d
      ## Dados SMTP
      - EMAIL_SMTP_USER=rafaelpedr@gmail.com
      - EMAIL_SMTP_PASSWORD=andmepddkljcdief
      - EMAIL_SMTP_HOST=smtp.gmail.com
      - EMAIL_SMTP_PORT=587
      - EMAIL_SMTP_IGNORE_TLS=true
      - EMAIL_FROM=rafaelpedr@gmail.com
      - EMAIL_TEMPLATES_PATH=/directus/templates
      ## Dados MinIO
      - STORAGE_LOCATIONS=s3
      - STORAGE_S3_DRIVER=s3
      - STORAGE_S3_KEY=MZoXK0EUSt2Ch1STuapj
      - STORAGE_S3_SECRET=4Zn7fozuno8EHyBC9Lov4snq5Q6TeFBfSC5mUFWg
      - STORAGE_S3_BUCKET=directus
      - STORAGE_S3_REGION=us-east-1
      - STORAGE_S3_ENDPOINT=s32.rafaelpedrosa.com.br
      - STORAGE_S3_FORCE_PATH_STYLE=true
      ## Redis
      - CACHE_ENABLED=true
      - CACHE_STORE=redis
      - CACHE_AUTO_PURGE=true
      - REDIS=redis://redis:6379/8
      ## Dados Postgres
      - DB_CLIENT=pg
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=directus2
      - DB_USER=postgres
      - DB_PASSWORD=bf6068b9d2207fe06ded952e8e16d349
      ## Cors
      - CORS_ENABLED=true
      - CORS_ORIGIN=true
      - CORS_METHODS=GET,POST,PATCH,DELETE
    volumes:
      - extensions2:/directus/extensions
      - templates2:/directus/templates

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.http.routers.directus2.service: "directus2"
        traefik.http.routers.directus2.rule: "Host(`directus2.rafaelpedrosa.com.br`)"
        traefik.http.services.directus2.loadbalancer.server.port: "8055"
        traefik.http.routers.directus2.entrypoints: "websecure"
        traefik.http.routers.directus2.tls.certresolver: "le"
    networks:
      - externa
      - interna
volumes:
  extensions2:
  templates2:

networks:
  interna:
    external: true
  externa:
    external: true
