services:
  postgres:
    image: postgres:16
    command:
      [
        postgres,
        --max_connections=300,
        --wal_level=minimal,
        --max_wal_senders=0,
        --listen_addresses=*,
      ]
    environment:
      - POSTGRES_PASSWORD=bf6068b9d2207fe06ded952e8e16d349
      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
    networks:
      - interna
      - externa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 2048M
    # Comente essa config caso nao deseje que bancos sejam criados automaticamente na primeira vez que iniciar o postgres
    configs:
      - source: entrypoint_postgres
        target: /docker-entrypoint-initdb.d/init-db.sh
        mode: 0755

  pgadmin4:
    image: "dpage/pgadmin4"
    restart: always
    #ports:
    #  - '5050:80'
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.pga.entrypoints: "websecure"
        traefik.http.routers.pga.tls.certresolver: "le"
        traefik.http.services.pga.loadbalancer.server.port: 80
        traefik.http.services.pga.loadbalancer.passHostHeader: "true"
        traefik.http.routers.pga.rule: "Host(`pgadmin2.rafaelpedrosa.com.br`)"
        traefik.http.routers.pga.service: "pga"
    environment:
      PGADMIN_DEFAULT_EMAIL: "rafaelpedr@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "bf6068b9d2207fe06ded952e8e16d349"
    networks:
      - interna
      - externa

volumes:
  postgres_data:
    external: true

configs:
  entrypoint_postgres:
    external: true

networks:
  interna:
    external: true
  externa:
    external: true
