x-variaveis: &variaveis
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "c04fa4ff7324c4edfc7a11ef6514e706"
  RABBITMQ_ERLANG_COOKIE: "server3" # Alterado para diferenciar
services:
  rabbitmq3: # Nome do serviço alterado
    image: rabbitmq:4.0.8-management
    hostname: rabbitmq3 # Hostname alterado
    environment:
      <<: *variaveis
    volumes:
      - rabbitmq_data3:/var/lib/rabbitmq/ # Volume alterado
    networks:
      - externa
      - interna
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.rabbitmq3.entrypoints: "websecure" # Nome do roteador alterado
        traefik.http.routers.rabbitmq3.tls.certresolver: "le"
        traefik.http.services.rabbitmq3.loadbalancer.server.port: 15672 # Mesmo porto interno
        traefik.http.routers.rabbitmq3.service: "rabbitmq3" # Nome do serviço alterado
        traefik.http.routers.rabbitmq3.rule: "Host(`rabbitmq3.rafaelpedrosa.com.br`)" # Domínio adaptado
volumes:
  rabbitmq_data3: # Nome do volume alterado
    external: false # Criará um novo volume
networks:
  externa:
    external: true
  interna:
    external: true
