services:
  traefik:
    image: traefik:v2.2.11
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode=true
      # Rede em que o Traefik irá rodar
      - --providers.docker.network=externa
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      # Config para SSL Lets Encrypt
      - --certificatesresolvers.le.acme.email=rafaelpedr@gmail.com
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      # Config para SSL Cloudflare
      - --certificatesresolvers.cf.acme.email=rafaelpedr@gmail.com
      - --certificatesresolvers.cf.acme.storage=/cloudflare/acme.json
      - --certificatesresolvers.cf.acme.dnschallenge=true
      - --certificatesresolvers.cf.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cf.acme.dnschallenge.delaybeforecheck=0
      - --certificatesresolvers.cf.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      # A API na verdade é o painel que fica na porta 8080 descomente caso queira ver as rotas no frontend
      - --log.level=DEBUG
      #- --api.insecure=true
      #- --api.dashboard=true
      # Global HTTP -> HTTPS

    environment:
      CF_API_KEY: "suachavedocloudflare"
      CF_API_EMAIL: "rafaelpedr@gmail.com"
    ports:
      - { target: 80, published: 80, mode: host, protocol: tcp }
      - { target: 443, published: 443, mode: host, protocol: tcp }
      #- "8080:8080" # porta do painel do traefik/api, caso queira ver todas as rotas.
    volumes:
      - traefik_certificates:/letsencrypt
      - traefik_certificates:/cloudflare
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - externa
volumes:
  traefik_certificates:
    external: true
networks:
  externa:
    external: true
